import { NextResponse } from 'next/server';
import { kvCommand, kvConfigured } from '@/lib/kv';
import { sendOutlookNotification } from '@/lib/microsoft';
import type { PlannerNotification, PublishFailure } from '@/lib/types';

const KEY='nce:notifications';
const LOG_KEY='nce:outlook-delivery-log';
const FAILURE_KEY='nce:publish-failures';

type DeliveryLog={id:string;to:string;subject:string;status:'sent'|'failed';message:string;createdAt:string};
type NotificationItem={id?:string;title?:string;channel?:string;segment?:string;status?:string;date?:string;approvalStatus?:string;description?:string;source?:string};

async function read():Promise<PlannerNotification[]>{if(!kvConfigured()) return [];const raw=await kvCommand<string|null>(['GET',KEY]);return raw?JSON.parse(raw):[]}
async function write(items:PlannerNotification[]){await kvCommand(['SET',KEY,JSON.stringify(items.slice(0,300))])}
async function writeDelivery(entry:DeliveryLog){if(!kvConfigured())return;const raw=await kvCommand<string|null>(['GET',LOG_KEY]);const items:DeliveryLog[]=raw?JSON.parse(raw):[];items.unshift(entry);await kvCommand(['SET',LOG_KEY,JSON.stringify(items.slice(0,100))])}
async function recordEmailFailure(notification:PlannerNotification,message:string){if(!kvConfigured())return;const raw=await kvCommand<string|null>(['GET',FAILURE_KEY]);const items:PublishFailure[]=raw?JSON.parse(raw):[];items.unshift({id:crypto.randomUUID(),channel:'Outlook',itemId:notification.itemId,title:`Email failed: ${notification.title}`,message,createdAt:new Date().toISOString(),retryCount:0});await kvCommand(['SET',FAILURE_KEY,JSON.stringify(items.slice(0,200))])}

function emailSuppressed(item?:NotificationItem){
  if(!item)return false;
  const isBlog=item.channel==='Website'&&(item.source==='Monthly Content Plan'||/^Blog(?:\s|$)/i.test(item.title||'')||String(item.id||'').includes('-blog-'));
  return isBlog;
}
function recipient(person:string){if(person==='Jenna')return process.env.JENNA_NOTIFICATION_EMAIL||'jhall@nce.com.au';if(person==='Kieren')return process.env.KIEREN_NOTIFICATION_EMAIL||'kbinion@nce.com.au';return ''}
function esc(value:unknown){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c))}
function melbourneDate(value?:string){if(!value)return'';try{return new Intl.DateTimeFormat('en-AU',{timeZone:'Australia/Melbourne',day:'numeric',month:'long',year:'numeric'}).format(new Date(`${value}T12:00:00+10:00`))}catch{return value}}
function emailHtml(notification:PlannerNotification,item?:NotificationItem){
  const root=(notification.link||'https://nce-marketing-planner.vercel.app').replace(/\/$/,'');
  const href=item?.id?`${root}/?item=${encodeURIComponent(item.id)}`:root;
  const rows=[['Channel',item?.channel],['Segment',item?.segment],['Workflow stage',item?.status],['Approval',item?.approvalStatus],['Planned date',melbourneDate(item?.date)]].filter(([,v])=>v);
  return `<!doctype html><html><body style="margin:0;background:#f2f2f2;font-family:Arial,sans-serif;color:#171717"><table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr><td align="center" style="padding:28px 12px"><table role="presentation" width="100%" style="max-width:620px;background:#fff;border:1px solid #dedede"><tr><td style="background:#111;padding:22px 28px;color:#fff"><div style="font-size:12px;letter-spacing:1.4px;text-transform:uppercase;color:#d42027;font-weight:700">NCE Marketing Planner</div><div style="font-size:24px;line-height:1.25;font-weight:700;margin-top:6px">${esc(notification.title)}</div></td></tr><tr><td style="padding:28px"><p style="font-size:16px;line-height:1.6;margin:0 0 22px">${esc(notification.message)}</p>${item?.title?`<div style="border-left:4px solid #d42027;background:#f7f7f7;padding:16px 18px;margin-bottom:22px"><div style="font-size:12px;text-transform:uppercase;letter-spacing:1px;color:#666;margin-bottom:5px">Campaign</div><div style="font-size:19px;font-weight:700">${esc(item.title)}</div></div>`:''}${rows.length?`<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin-bottom:24px">${rows.map(([k,v])=>`<tr><td style="padding:8px 0;border-bottom:1px solid #ececec;color:#666;width:42%">${esc(k)}</td><td style="padding:8px 0;border-bottom:1px solid #ececec;font-weight:600">${esc(v)}</td></tr>`).join('')}</table>`:''}${item?.description?`<div style="font-size:14px;line-height:1.6;color:#444;margin-bottom:24px"><strong style="color:#171717">Scope:</strong> ${esc(item.description)}</div>`:''}<a href="${esc(href)}" style="display:inline-block;background:#d42027;color:#fff;text-decoration:none;padding:13px 18px;font-weight:700">Open this item in the dashboard</a><p style="font-size:12px;color:#777;margin:24px 0 0">Sent automatically by the NCE FY27 Marketing Planner.</p></td></tr></table></td></tr></table></body></html>`
}
async function sendEmail(notification:PlannerNotification,item?:NotificationItem){if(emailSuppressed(item))return {to:'',subject:'',suppressed:true};const to=recipient(notification.person);if(!to)return {to:'',subject:''};const subject=`NCE Marketing: ${notification.title}`;await sendOutlookNotification(to,subject,emailHtml(notification,item));return {to,subject,suppressed:false}}
export async function GET(request:Request){const person=new URL(request.url).searchParams.get('person');const items=await read();return NextResponse.json({configured:kvConfigured(),notifications:person?items.filter(item=>item.person===person):items})}
export async function POST(request:Request){try{const body=await request.json();const item:NotificationItem|undefined=body.item;const notification:PlannerNotification={id:crypto.randomUUID(),person:body.person,title:body.title,message:body.message,itemId:body.itemId,link:body.link,createdAt:new Date().toISOString()};if(kvConfigured()){const items=await read();items.unshift(notification);await write(items)}let emailSent=false;let emailError='';let emailTo='';let emailSuppressedForItem=false;try{const sent=await sendEmail(notification,item);emailTo=sent.to;emailSuppressedForItem=Boolean(sent.suppressed);if(sent.to){emailSent=true;await writeDelivery({id:crypto.randomUUID(),to:sent.to,subject:sent.subject,status:'sent',message:'Accepted by Microsoft Graph.',createdAt:new Date().toISOString()})}}catch(error){emailError=error instanceof Error?error.message:'Outlook notification failed.';emailTo=recipient(notification.person);await writeDelivery({id:crypto.randomUUID(),to:emailTo,subject:`NCE Marketing: ${notification.title}`,status:'failed',message:emailError,createdAt:new Date().toISOString()});await recordEmailFailure(notification,emailError)}return NextResponse.json({notification,emailSent,emailError,emailTo,emailSuppressed:emailSuppressedForItem})}catch(error){return NextResponse.json({error:error instanceof Error?error.message:'Unable to create notification'},{status:500})}}
export async function PATCH(request:Request){const body=await request.json();const items=await read();const now=new Date().toISOString();const next=items.map(item=>(body.id===item.id||body.all&&item.person===body.person)?{...item,readAt:now}:item);if(kvConfigured()) await write(next);return NextResponse.json({notifications:next})}
