'use client';
import { useEffect,useState } from 'react';
import { Check, MessageSquare, RotateCcw, Send } from 'lucide-react';
import type { PlannerComment, PlannerItem } from '@/lib/types';
import { formatMelbourne } from '@/lib/time';

export default function CollaborationPanel({item,currentPerson,onUpdate}:{item:PlannerItem,currentPerson:string,onUpdate:(item:PlannerItem)=>void}){
  const [comments,setComments]=useState<PlannerComment[]>([]);const [message,setMessage]=useState('');const [kind,setKind]=useState<'Comment'|'Change request'>('Comment');const [busy,setBusy]=useState(false);
  async function load(){const r=await fetch(`/api/comments?itemId=${encodeURIComponent(item.id)}`,{cache:'no-store'});const b=await r.json();setComments(b.comments||[])}
  useEffect(()=>{void load()},[item.id]);
  async function notify(person:string,title:string,text:string){await fetch('/api/notifications',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({person,itemId:item.id,title,message:text,link:window.location.origin,item})}).catch(()=>{})}
  async function submit(){if(!message.trim())return;setBusy(true);try{const r=await fetch('/api/comments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({itemId:item.id,author:currentPerson,message,kind})});const b=await r.json();if(!r.ok)throw new Error(b.error);setComments(prev=>[b.comment,...prev]);setMessage('');if(kind==='Change request'){onUpdate({...item,status:'Changes Required',approvalStatus:'Changes requested'});await notify(item.assetCreator||'Kieren',`Changes requested: ${item.title}`,`${currentPerson}: ${message.trim()}`)}else{const person=currentPerson==='Jenna'?(item.assetCreator||'Kieren'):(item.approver||'Jenna');await notify(person,`New comment: ${item.title}`,`${currentPerson}: ${message.trim()}`)}}finally{setBusy(false)}}
  async function resolve(comment:PlannerComment){const resolve=!comment.resolvedAt;const r=await fetch('/api/comments',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({itemId:item.id,commentId:comment.id,resolve,person:currentPerson})});const b=await r.json();setComments(b.comments||comments);if(resolve&&comment.kind==='Change request')await notify(item.approver||'Jenna',`Changes completed: ${item.title}`,`${currentPerson} marked a change request as resolved.`)}
  return <section className="drawer-section collaboration-panel"><div className="section-heading"><div><h4>Comments and change requests</h4><p>Keep review notes and revisions attached to this item.</p></div><MessageSquare size={19}/></div><div className="comment-compose"><div className="comment-type"><button className={kind==='Comment'?'active':''} onClick={()=>setKind('Comment')}>Comment</button><button className={kind==='Change request'?'active change':''} onClick={()=>setKind('Change request')}>Request changes</button></div><textarea rows={3} value={message} onChange={e=>setMessage(e.target.value)} placeholder={`Write as ${currentPerson}…`}/><button className="btn primary" disabled={busy||!message.trim()} onClick={submit}><Send size={15}/>{busy?'Saving…':'Add note'}</button></div><div className="comment-list">{comments.length===0?<div className="empty-files"><MessageSquare size={20}/><span>No comments yet</span></div>:comments.map(comment=><article key={comment.id} className={`comment-card ${comment.kind==='Change request'?'change-request':''} ${comment.resolvedAt?'resolved':''}`}><header><div><strong>{comment.author}</strong><span>{comment.kind}</span></div><time>{formatMelbourne(comment.createdAt)}</time></header><p>{comment.message}</p>{comment.kind==='Change request'&&<button onClick={()=>resolve(comment)}>{comment.resolvedAt?<><RotateCcw size={14}/>Reopen</>:<><Check size={14}/>Mark resolved</>}</button>}</article>)}</div></section>
}
