'use client';

import { melbourneLocalToUtc, utcToMelbourneInput } from '@/lib/time';
import {useEffect,useMemo,useRef,useState} from 'react';
import {CalendarClock,CheckCircle2,ChevronLeft,ChevronRight,Facebook,GripVertical,ImagePlus,Instagram,LoaderCircle,RefreshCw,Send,Trash2,UploadCloud,XCircle} from 'lucide-react';
import type {MetaMediaAsset,PlannerItem} from '@/lib/types';
import type {StoredMetaJob} from '@/lib/meta-schedule';

type PostType='image'|'carousel';

export default function MetaPanel({item,onUpdate}:{item:PlannerItem;onUpdate:(item:PlannerItem)=>void}){
  const [connected,setConnected]=useState(false);const [configured,setConfigured]=useState<boolean|null>(null);const [loading,setLoading]=useState(false);const [uploading,setUploading]=useState(false);const [message,setMessage]=useState('');const [scheduledJob,setScheduledJob]=useState<StoredMetaJob|null>(null);const [unscheduling,setUnscheduling]=useState(false);
  const [pageName,setPageName]=useState('');const [instagramName,setInstagramName]=useState('');
  const [platforms,setPlatforms]=useState<string[]>(item.metaPlatforms??['Facebook','Instagram']);
  const [copy,setCopy]=useState(item.metaCaption??'');
  const [assets,setAssets]=useState<MetaMediaAsset[]>(item.metaMediaAssets??[]);
  const [postType,setPostType]=useState<PostType>(item.metaPostType==='carousel'?'carousel':'image');
  const [scheduledAt,setScheduledAt]=useState(utcToMelbourneInput(item.metaScheduledAt)||`${item.date}T10:00`);
  const [previewIndex,setPreviewIndex]=useState(0);const [previewPlatform,setPreviewPlatform]=useState<'Instagram'|'Facebook'>('Instagram');
  const [dragIndex,setDragIndex]=useState<number|null>(null);const fileRef=useRef<HTMLInputElement>(null);

  async function loadScheduled(){try{const r=await fetch(`/api/meta/scheduled?itemId=${encodeURIComponent(item.id)}`,{cache:'no-store'});const b=await r.json();setScheduledJob(b.job??null)}catch{}}
  async function load(){setLoading(true);setMessage('');try{const r=await fetch('/api/meta/status');const b=await r.json();setConfigured(Boolean(b.configured));setConnected(Boolean(b.connected));setPageName(b.page?.name??'');setInstagramName(b.instagram?.username??'');if(!b.connected)setMessage(b.error??'Add Meta credentials in Vercel.');}catch(e){setMessage(e instanceof Error?e.message:'Meta connection failed');}finally{setLoading(false)}}
  useEffect(()=>{void load();void loadScheduled()},[]);
  useEffect(()=>{setAssets(item.metaMediaAssets??[]);setCopy(item.metaCaption??'');setPreviewIndex(0);void loadScheduled()},[item.id]);
  useEffect(()=>{if(assets.length>1)setPostType('carousel');else if(assets.length===1)setPostType('image')},[assets.length]);
  function toggle(platform:string){setPlatforms(v=>v.includes(platform)?v.filter(x=>x!==platform):[...v,platform])}
  function absoluteUrl(url:string){return url.startsWith('/')?`${window.location.origin}${url}`:url}
  function commit(next:MetaMediaAsset[],notice?:string){setAssets(next);setPreviewIndex(i=>Math.min(i,Math.max(0,next.length-1)));onUpdate({...item,metaMediaAssets:next,metaMediaUrls:next.map(a=>absoluteUrl(a.url)),metaMediaUrl:next[0]?absoluteUrl(next[0].url):undefined,metaPostType:next.length>1?'carousel':'image'});if(notice)setMessage(notice)}
  async function upload(files:FileList|File[]|null){if(!files||files.length===0)return;setUploading(true);setMessage('');try{const added:MetaMediaAsset[]=[];for(const file of Array.from(files)){const form=new FormData();form.set('file',file);form.set('itemId',item.id);const r=await fetch('/api/meta/assets',{method:'POST',body:form});const b=await r.json();if(!r.ok)throw new Error(b.error||`Unable to upload ${file.name}`);added.push(b.asset)}commit([...assets,...added],`${added.length} scheduling image${added.length===1?'':'s'} uploaded.`)}catch(e){setMessage(e instanceof Error?e.message:'Image upload failed.')}finally{setUploading(false)}}
  async function remove(asset:MetaMediaAsset){setUploading(true);setMessage('');try{const r=await fetch(`/api/meta/assets?id=${encodeURIComponent(asset.id)}`,{method:'DELETE'});const b=await r.json();if(!r.ok)throw new Error(b.error||'Unable to remove image');commit(assets.filter(a=>a.id!==asset.id),'Scheduling image removed.')}catch(e){setMessage(e instanceof Error?e.message:'Unable to remove image.')}finally{setUploading(false)}}
  function move(from:number,to:number){if(from===to||to<0||to>=assets.length)return;const next=[...assets];const [picked]=next.splice(from,1);next.splice(to,0,picked);commit(next,'Carousel order updated.')}
  function onDrop(index:number){if(dragIndex===null)return;move(dragIndex,index);setDragIndex(null)}
  function saveDraft(){const urls=assets.map(a=>absoluteUrl(a.url));onUpdate({...item,metaPlatforms:platforms,metaCaption:copy,metaPostType:assets.length>1?'carousel':'image',metaMediaAssets:assets,metaMediaUrls:urls,metaMediaUrl:urls[0],metaSourceUrl:undefined,metaLinkUrl:undefined,metaScheduledAt:scheduledAt?melbourneLocalToUtc(scheduledAt).toISOString():undefined,status:item.status==='Brief Required'?'In Production':item.status});setMessage('Organic post copy and scheduling images saved for review.')}
  async function schedule(){setLoading(true);setMessage('');try{const mediaUrls=assets.map(a=>absoluteUrl(a.url));const finalType:PostType=mediaUrls.length>1?'carousel':'image';const r=await fetch('/api/meta/schedule',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({platforms,message:copy,postType:finalType,mediaUrls,mediaUrl:mediaUrls[0]??'',scheduledAt:melbourneLocalToUtc(scheduledAt).toISOString(),approvalStatus:item.approvalStatus,itemId:item.id})});const b=await r.json();if(!r.ok)throw new Error(b.error||'Unable to schedule post');setScheduledJob(b.job);onUpdate({...item,status:'Scheduled',metaPlatforms:platforms,metaCaption:copy,metaPostType:finalType,metaMediaAssets:assets,metaMediaUrls:mediaUrls,metaMediaUrl:mediaUrls[0],metaScheduledAt:b.job.scheduledAt,metaJobId:b.job.id,metaStatus:b.job.status});setMessage(b.longRange?'Post planned. It will automatically enter the QStash queue when it is within six days of publishing.':'Post queued for publishing at the selected Melbourne time.')}catch(e){setMessage(e instanceof Error?e.message:'Unable to schedule post');}finally{setLoading(false)}}
  async function unschedule(){if(!confirm('Unschedule this Meta post? The copy and images will be kept.'))return;setUnscheduling(true);setMessage('');try{const r=await fetch('/api/meta/scheduled',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({itemId:item.id})});const b=await r.json();if(!r.ok)throw new Error(b.error||'Unable to unschedule post');setScheduledJob(null);onUpdate({...item,status:'Approved',metaJobId:undefined,metaStatus:undefined,metaScheduledAt:undefined});setMessage('Post unscheduled. The copy and final images are still saved.')}catch(e){setMessage(e instanceof Error?e.message:'Unable to unschedule post')}finally{setUnscheduling(false)}}
  function melbourneScheduleLabel(value:string){return new Intl.DateTimeFormat('en-AU',{timeZone:'Australia/Melbourne',weekday:'short',day:'numeric',month:'long',year:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(value))}
  const active=assets[Math.min(previewIndex,Math.max(0,assets.length-1))];

  return <section className="drawer-section meta-panel">
    <div className="meta-heading"><div><span className="integration-kicker">META ORGANIC</span><h4>Facebook and Instagram review & scheduling</h4><p>Use the shared HTML below for approval, then drag in the final exported post images here for scheduling.</p></div><button className="icon-btn" type="button" onClick={()=>void load()} disabled={loading}>{loading?<LoaderCircle className="spin" size={18}/>:<RefreshCw size={18}/>}</button></div>
    <div className={`connection-state ${connected?'connected':'disconnected'}`}>{connected?<CheckCircle2 size={17}/>:<Facebook size={17}/>}<strong>{connected?`Meta connected${pageName?` · ${pageName}`:''}${instagramName?` / @${instagramName}`:''}`:configured===false?'Meta not configured':'Meta unavailable'}</strong></div>
    {connected&&<>
      <div className="platform-select"><button type="button" className={platforms.includes('Facebook')?'active':''} onClick={()=>toggle('Facebook')}><Facebook size={18}/>Facebook</button><button type="button" className={platforms.includes('Instagram')?'active':''} onClick={()=>toggle('Instagram')}><Instagram size={18}/>Instagram</button></div>
      <label className="integration-field"><span>Post copy</span><textarea rows={8} value={copy} onChange={e=>setCopy(e.target.value)} placeholder="Write or paste the final post copy here."/></label>
      <div className="meta-upload-block"><div className="section-heading"><div><h4>Final scheduling images</h4><p>Drag and drop exported PNG, JPG or WebP files. Reorder them below; that order becomes the carousel order.</p></div><button type="button" className="upload-button button-upload" onClick={()=>fileRef.current?.click()} disabled={uploading}><UploadCloud size={17}/>{uploading?'Uploading…':'Add images'}</button><input ref={fileRef} hidden multiple type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{void upload(e.target.files);e.currentTarget.value=''}}/></div>
        <div className={`meta-drop-zone ${uploading?'busy':''}`} onDragOver={e=>{e.preventDefault();e.dataTransfer.dropEffect='copy'}} onDrop={e=>{e.preventDefault();void upload(e.dataTransfer.files)}} onClick={()=>!uploading&&fileRef.current?.click()}><ImagePlus size={25}/><strong>Drop final post images here</strong><span>Up to 8 MB per image · click to browse</span></div>
        {assets.length>0&&<div className="meta-asset-order">{assets.map((asset,index)=><div key={asset.id} className={`meta-asset-card ${dragIndex===index?'dragging':''}`} draggable onDragStart={()=>setDragIndex(index)} onDragEnd={()=>setDragIndex(null)} onDragOver={e=>e.preventDefault()} onDrop={()=>onDrop(index)}><span className="asset-order-number">{index+1}</span><GripVertical className="asset-grip" size={18}/><img src={asset.url} alt={`Scheduling image ${index+1}`}/><div><strong>{asset.fileName}</strong><span>{Math.round(asset.size/1024)} KB · {index===0?'First image':'Carousel slide '+(index+1)}</span></div><div className="asset-order-actions"><button type="button" onClick={()=>move(index,index-1)} disabled={index===0} aria-label="Move image earlier"><ChevronLeft size={16}/></button><button type="button" onClick={()=>move(index,index+1)} disabled={index===assets.length-1} aria-label="Move image later"><ChevronRight size={16}/></button><button type="button" onClick={()=>void remove(asset)} aria-label="Remove image"><Trash2 size={16}/></button></div></div>)}</div>}
      </div>
      <label className="integration-field"><span>Publish date and time (Melbourne)</span><input type="datetime-local" value={scheduledAt} onChange={e=>setScheduledAt(e.target.value)}/></label>
      <div className="meta-review-block"><div className="meta-review-toolbar"><div><span className="integration-kicker">POST PREVIEW</span><strong>{assets.length>1?`${assets.length} image carousel`:assets.length===1?'Single image post':'Awaiting final images'}</strong></div><div className="preview-platform-tabs"><button type="button" className={previewPlatform==='Instagram'?'active':''} onClick={()=>setPreviewPlatform('Instagram')}><Instagram size={15}/>Instagram</button><button type="button" className={previewPlatform==='Facebook'?'active':''} onClick={()=>setPreviewPlatform('Facebook')}><Facebook size={15}/>Facebook</button></div></div>
        <div className={`social-post-preview ${previewPlatform.toLowerCase()}`}><div className="social-preview-account"><div className="social-avatar">NCE</div><div><strong>{previewPlatform==='Instagram'?(instagramName?`@${instagramName}`:'@nce_rv_specialist'):(pageName||'NCE RV Specialist')}</strong><span>Organic post preview</span></div></div><div className="social-preview-media">{!active&&<div className="media-empty">Drop the final exported post images above.</div>}{active&&<img src={active.url} alt={`Post preview ${previewIndex+1}`}/>} {assets.length>1&&<><button className="carousel-nav prev" type="button" onClick={()=>setPreviewIndex(i=>(i-1+assets.length)%assets.length)} aria-label="Previous image"><ChevronLeft size={20}/></button><button className="carousel-nav next" type="button" onClick={()=>setPreviewIndex(i=>(i+1)%assets.length)} aria-label="Next image"><ChevronRight size={20}/></button><div className="carousel-count">{previewIndex+1}/{assets.length}</div></>}</div>{assets.length>1&&<div className="carousel-dots">{assets.map((_,index)=><button key={index} type="button" className={index===previewIndex?'active':''} onClick={()=>setPreviewIndex(index)} aria-label={`View image ${index+1}`}/>)}</div>}<div className="social-preview-copy"><p>{copy||'Saved post copy will appear here.'}</p></div></div>
      </div>
      {scheduledJob&&<div className={`meta-schedule-state ${scheduledJob.status.toLowerCase()}`}><div><CalendarClock size={18}/><div><span>META SCHEDULE</span><strong>{scheduledJob.status==='Planned'?'Planned in dashboard':scheduledJob.status==='Queued'?'Queued with QStash':scheduledJob.status}</strong><p>{melbourneScheduleLabel(scheduledJob.scheduledAt)} · Melbourne time</p>{scheduledJob.status==='Planned'&&<small>More than seven days away. The planner will queue it automatically when it enters the six-day window.</small>}{scheduledJob.error&&<small>{scheduledJob.error}</small>}</div></div>{scheduledJob.status!=='Published'&&<button type="button" onClick={()=>void unschedule()} disabled={unscheduling}><XCircle size={15}/>{unscheduling?'Unscheduling…':'Unschedule post'}</button>}</div>}
      <div className="integration-actions"><button className="btn secondary" type="button" onClick={saveDraft}>Save draft</button><button className="btn primary" type="button" onClick={()=>void schedule()} disabled={loading||Boolean(scheduledJob&&scheduledJob.status!=='Failed')||platforms.length===0||!copy.trim()||assets.length===0||item.approvalStatus!=='Approved'}><Send size={16}/>Schedule organic post</button>{item.approvalStatus!=='Approved'&&<small>Jenna must approve this item first.</small>}{assets.length===0&&<small>Add at least one final scheduling image.</small>}</div>
    </>}
    {message&&<p className="integration-message">{message}</p>}
  </section>
}
