'use client';

import { useMemo, useState } from 'react';
import { addDays, format, parseISO } from 'date-fns';
import { BarChart3, RefreshCw } from 'lucide-react';
import type { PlannerItem, PlannerPerformance } from '@/lib/types';

type SyncResponse={performance?:PlannerPerformance;sources?:Record<string,{matched?:number;metrics?:Record<string,number>}>;warnings?:string[];confidence?:'high'|'medium'|'low';matchedSourceCount?:number;note?:string;error?:string};
type MetricDef={key:keyof PlannerPerformance;label:string;kind?:'number'|'currency'|'percent'};

function medium(item:PlannerItem){const f=item.contentFormat||'';const blogText=[item.description,item.performance?.notes,item.title].filter(Boolean).join(' ');const isBlog=f==='Blog'||/https?:\/\/(?:www\.)?nce\.com\.au\/blog\//i.test(blogText);if(item.channel==='Email'||f==='EDM')return'Email';if(item.channel==='Organic'||['Meta Static','Meta Carousel','Meta Video'].includes(f))return'Meta organic';if(item.channel==='LinkedIn')return'LinkedIn organic';if(isBlog)return'Blog';if(item.channel==='Website'||['Landing Page','Website Update','Product Page'].includes(f))return item.productSkus?.length?'Product / ecommerce':'Website';if(item.channel==='Video'||f==='Video')return'Video';if(item.channel==='Print'||f==='Flyer')return'Print';return'General'}
function metricDefs(item:PlannerItem):MetricDef[]{switch(medium(item)){case'Email':return[{key:'sent',label:'Sent'},{key:'delivered',label:'Delivered'},{key:'opens',label:'Unique opens'},{key:'openRate',label:'Open rate',kind:'percent'},{key:'emailClicks',label:'Unique clicks'},{key:'clickRate',label:'Click rate',kind:'percent'},{key:'ctor',label:'Click-to-open rate',kind:'percent'},{key:'unsubscribes',label:'Unsubscribes'},{key:'unsubscribeRate',label:'Unsubscribe rate',kind:'percent'},{key:'bounces',label:'Bounces'},{key:'purchases',label:'Orders'},{key:'revenue',label:'Revenue',kind:'currency'}];case'Meta organic':return[{key:'reach',label:'Reach'},{key:'impressions',label:'Impressions'},{key:'views',label:'Views'},{key:'reactions',label:'Facebook reactions'},{key:'likes',label:'Instagram likes'},{key:'comments',label:'Comments'},{key:'shares',label:'Shares'},{key:'saves',label:'Saves'},{key:'engagements',label:'Engagements'},{key:'engagementRate',label:'Engagement rate',kind:'percent'},{key:'videoViews',label:'Video views'}];case'LinkedIn organic':return[{key:'impressions',label:'Impressions'},{key:'views',label:'Views'},{key:'reactions',label:'Reactions'},{key:'comments',label:'Comments'},{key:'shares',label:'Reposts / shares'},{key:'linkClicks',label:'Link clicks'},{key:'engagements',label:'Engagements'},{key:'engagementRate',label:'Engagement rate',kind:'percent'}];case'Blog':return[{key:'sessions',label:'Sessions'},{key:'users',label:'Active users'},{key:'engagedSessions',label:'Engaged sessions'},{key:'engagementRate',label:'Engagement rate',kind:'percent'},{key:'averageSessionDuration',label:'Avg session duration (sec)'},{key:'purchases',label:'Purchases'},{key:'revenue',label:'Purchase revenue',kind:'currency'}];case'Product / ecommerce':return[{key:'productViews',label:'Product views'},{key:'addToCarts',label:'Add to carts'},{key:'purchases',label:'Units purchased'},{key:'conversionRate',label:'View → purchase rate',kind:'percent'},{key:'revenue',label:'Net revenue ex GST',kind:'currency'}];case'Website':return[{key:'sessions',label:'Sessions'},{key:'users',label:'Active users'},{key:'purchases',label:'Purchases'},{key:'conversionRate',label:'Session conversion rate',kind:'percent'},{key:'revenue',label:'Purchase revenue',kind:'currency'}];case'Video':return[{key:'views',label:'Views'},{key:'reach',label:'Reach'},{key:'engagements',label:'Engagements'},{key:'engagementRate',label:'Engagement rate',kind:'percent'},{key:'comments',label:'Comments'},{key:'shares',label:'Shares'}];default:return[]}}
function display(value:number|undefined,kind:MetricDef['kind']){if(value===undefined)return'—';if(kind==='currency')return new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD',maximumFractionDigits:2}).format(value);if(kind==='percent')return`${(value*100).toFixed(1)}%`;return new Intl.NumberFormat('en-AU',{maximumFractionDigits:1}).format(value)}

export default function PerformanceSync({item,onUpdate}:{item:PlannerItem;onUpdate:(item:PlannerItem)=>void}){
  const fallbackEnd=useMemo(()=>format(addDays(parseISO(item.date),6),'yyyy-MM-dd'),[item.date]);
  const [start,setStart]=useState(item.performance?.analyticsWindowStart||item.date);const [end,setEnd]=useState(item.performance?.analyticsWindowEnd||item.endDate||fallbackEnd);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [warnings,setWarnings]=useState<string[]>([]);const [sources,setSources]=useState<string[]>(item.performance?.analyticsSources??[]);
  const currentMedium=medium(item);const defs=metricDefs(item);const performance=item.performance??{};
  function editMetric(def:MetricDef,value:string){const parsed=value===''?undefined:Number(value);onUpdate({...item,performance:{...performance,[def.key]:parsed,analyticsMedium:currentMedium}})}
  async function pull(){setBusy(true);setMessage('');setWarnings([]);try{const response=await fetch('/api/performance',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({itemId:item.id,start,end,title:item.title,channel:item.channel,contentFormat:item.contentFormat,description:item.description,notes:item.performance?.notes,productSkus:item.productSkus??[],dotdigitalCampaignId:item.dotdigitalCampaignId,dotdigitalCampaignName:item.dotdigitalCampaignName,metaCaption:item.metaCaption})});const text=await response.text();let body:SyncResponse={};try{body=text?JSON.parse(text):{}}catch{throw new Error(text||'Unable to read analytics response.')}if(!response.ok)throw new Error(body.error||'Unable to pull campaign performance.');const matchedSources=Object.entries(body.sources??{}).filter(([,source])=>Number(source?.matched||0)>0).map(([name])=>name);const pulled=body.performance??{};const next:PlannerPerformance={...performance,...pulled,analyticsLastSyncedAt:new Date().toISOString(),analyticsConfidence:body.confidence,analyticsWindowStart:start,analyticsWindowEnd:end,analyticsSources:matchedSources,analyticsMedium:currentMedium};setWarnings(body.warnings??[]);setSources(matchedSources);setMessage(matchedSources.length?`Pulled ${currentMedium} results from ${matchedSources.join(' + ')}.`:body.note||`No matching ${currentMedium} analytics found.`);onUpdate({...item,performance:next})}catch(error){setMessage(error instanceof Error?error.message:'Unable to pull performance.')}finally{setBusy(false)}}
  const autoSupported=!['Print','General'].includes(currentMedium);
  return <div className="performance-sync medium-performance">
    <div className="performance-sync-head"><div><BarChart3 size={17}/><span><strong>{currentMedium} performance</strong><small>{currentMedium==='Email'?'Dotdigital campaign metrics':currentMedium==='Meta organic'?'Facebook + Instagram organic post insights':currentMedium==='LinkedIn organic'?'LinkedIn organic post metrics':currentMedium==='Blog'?'Exact blog URL in notes → GA4 page performance':currentMedium==='Product / ecommerce'?'GA4 product behaviour + BigCommerce sales':currentMedium==='Website'?'GA4 website performance':'Medium-specific results'}</small></span></div>{autoSupported&&<button type="button" className="btn secondary" onClick={()=>void pull()} disabled={busy}><RefreshCw size={15} className={busy?'spin':''}/>{busy?'Pulling…':item.performance?.analyticsLastSyncedAt?'Refresh results':'Pull performance'}</button>}</div>
    {autoSupported&&<div className="performance-window"><label><span>Stats from</span><input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label><span>Stats to</span><input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label></div>}
    {defs.length>0?<div className="medium-metric-grid">{defs.map(def=><label key={String(def.key)}><span>{def.label}</span><strong>{display(performance[def.key] as number|undefined,def.kind)}</strong><input aria-label={`Edit ${def.label}`} type="number" step="any" value={(performance[def.key] as number|undefined)??''} onChange={e=>editMetric(def,e.target.value)}/></label>)}</div>:<p className="sync-message">No automatic KPI set is required for this medium. Use the notes field for outcomes.</p>}
    {item.performance?.analyticsLastSyncedAt&&<small className="sync-meta">Last synced {new Date(item.performance.analyticsLastSyncedAt).toLocaleString('en-AU')} · Confidence: {item.performance.analyticsConfidence??'unknown'}{sources.length?` · ${sources.join(', ')}`:''}</small>}
    {message&&<p className="sync-message">{message}</p>}{warnings.length>0&&<div className="sync-warnings">{warnings.map(warning=><small key={warning}>{warning}</small>)}</div>}
  </div>
}
